<?php

function oc_page_unlimited_field_display_alter(&$display, $context)
{
    $term_no_side_meny = taxonomy_get_term_by_name("Uden venstre menu og højre sektion (1 kolonne)");
    $term_left_menu = taxonomy_get_term_by_name("Med venstre menu (2 kolonner)");
    $term_right_menu = taxonomy_get_term_by_name("Med højre sektion (2 kolonner)");
    
    $term = reset($term_no_side_meny);
    $termid = isset( $context["entity"]->field_side_layout) ? $context["entity"]->field_side_layout['und'][0]['tid'] : -1;
    $field_name = $context['field']['field_name'];
    if(strcmp($field_name,"field_ding_page_title_image") == 0 && $termid == $term->tid)
    {
        $display['settings']['image_style'] = "page_layout_full_page";
    }
    if(strcmp($field_name,"field_ding_page_title_image") == 0 && ($termid == reset($term_right_menu)->tid || $termid == reset($term_left_menu)->tid ))
    {
        $display['settings']['image_style'] = "page_layout_one_side_menu";
    }
}
